server:
  port: 8222
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true 
      routes:
        - id: school
          uri: http://localhost:8070
          predicates: 
            - Path=/api/v1/schools/**
        - id: student
          uri: http://localhost:8071
          predicates: 
            - Path=/api/v1/students/**

