server:
  port: 8070
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/eureka
    username: thienan
    password: 2302
application:
  config:
    student-url: http://localhost:8222/api/v1/students

