server:
  port: 8071
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  application:
    name: student
  jpa:
      database: postgresql
      hibernate:
        ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/eureka
    username: thienan
    password: 2302
